### ISSUE TITLE
Knowledge Point listing error

### ISSUE THREAD

**Issue by RM44138** [tom1199/xinq-web-app#2]
Logged in as SA, 
1) Clicked on Roles screen- Roles are listed 
2) Clicked on the Home hyperlink above - Knowledge points are not listed
![pic3](https://user-images.githubusercontent.com/46082868/50382214-292b1200-06d5-11e9-9bc0-5aec88495786.jpg)
![pic4](https://user-images.githubusercontent.com/46082868/50382215-2c260280-06d5-11e9-8612-d40f26b5670f.jpg)

**Comment by tom1199** [comment]
@RM44138 can not be reproduced in the latest build
