### ISSUE TITLE
System hanged. No response for more than 120s for the below scenario.

### ISSUE THREAD

**Issue by RM44138** [tom1199/xinq-web-app#3]
1.	User logged in with Expert role to the system.
2.	In the ‘Knowledge Points Detail Screen’ user filled in the knowledge point information.
3.	In the category field, user selected ‘New Category’ Option
4.	In the ‘Category Detail screen’ user entered Category Name and Category Description
![pic5](https://user-images.githubusercontent.com/46082868/50382228-698a9000-06d5-11e9-8212-f477b04079f9.jpg)

**Comment by tom1199** [comment]
@RM44138 what is the issue here ?

**Comment by tom1199** [comment]
@RM44138 can not be reproduced in the latest version
